// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwvhlhYKMXG9lep4iiuHh0JVzjSY2kBE',
    appId: '1:1037560476724:web:0bc193c67ea638a6918661',
    messagingSenderId: '1037560476724',
    projectId: 'iotlab-f212a',
    authDomain: 'iotlab-f212a.firebaseapp.com',
    databaseURL: 'https://iotlab-f212a-default-rtdb.firebaseio.com',
    storageBucket: 'iotlab-f212a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLw1dQd2QufxJZaqv1q01n2ZSlJBlGl6g',
    appId: '1:1037560476724:android:f7f4ab46466bab1a918661',
    messagingSenderId: '1037560476724',
    projectId: 'iotlab-f212a',
    databaseURL: 'https://iotlab-f212a-default-rtdb.firebaseio.com',
    storageBucket: 'iotlab-f212a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtVA5xdFeYGk2c1haYmRxnzN12ckUc6Y',
    appId: '1:1037560476724:ios:7baf7f911b35093b918661',
    messagingSenderId: '1037560476724',
    projectId: 'iotlab-f212a',
    databaseURL: 'https://iotlab-f212a-default-rtdb.firebaseio.com',
    storageBucket: 'iotlab-f212a.appspot.com',
    iosBundleId: 'com.example.theiotlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEtVA5xdFeYGk2c1haYmRxnzN12ckUc6Y',
    appId: '1:1037560476724:ios:7baf7f911b35093b918661',
    messagingSenderId: '1037560476724',
    projectId: 'iotlab-f212a',
    databaseURL: 'https://iotlab-f212a-default-rtdb.firebaseio.com',
    storageBucket: 'iotlab-f212a.appspot.com',
    iosBundleId: 'com.example.theiotlab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwQ4iw5qh5Op_WjmK_OTx1O9uhcv8GaNA',
    appId: '1:1037560476724:web:1ae4018cccdb7f35918661',
    messagingSenderId: '1037560476724',
    projectId: 'iotlab-f212a',
    authDomain: 'iotlab-f212a.firebaseapp.com',
    databaseURL: 'https://iotlab-f212a-default-rtdb.firebaseio.com',
    storageBucket: 'iotlab-f212a.appspot.com',
  );
}
